### PR TITLE
GitHub Actions: use Agg backend for matplotlib

### LINKED ISSUE #253: Add/fix plot methods to Datasets
The following benchmark datasets need `plot(...)` methods:

- [x] ADVANCE (#264)
- [x] BeninSmallHolderCashews (#264)
- [x] BigEarthNet (#264)
- [x] COWC (#300)
- [x] CV4AKenyaCropType (#312)
- [x] TropicalCycloneWindEstimation (#298)
- [x] GID15 (#288)
- [x] LEVIRCDPlus (#335)
- [x] VHR10 (#798)
- [x] PatternNet (#314)
- [x] SEN12MS (#320)
- [x] SpaceNet (#252, #311)
- [x] ZueriCrop (#334)

Further, the `plot(...)` methods of RasterDataset and VectorDataset need to be removed, and added individually to:

- [x] CanadianBuildingFootprints (#410)
- [x] CDL (#415)
- [x] NAIP (#407)
- [x] Landsat (#661)
- [x] ChesapeakeCVPR (#820)
- [x] Sentinel (#416)

The `ChesapeakeCVPR` dataset is a bit of an outlier as it is a `GeoDataset`. I need to think more about that.

### PR DESCRIPTION
**Pull request by calebrob6**

### CODE REVIEW

**Comment by calebrob6** [comment]
The recent series of commits on this PR were to check to see if matplotlib would behave as expected with environment variables set in the github actions yaml files.

Specifically, I added a new `tests/tmp` action to "tests.yaml" that ran a `tmp.py` script that printed the backend that matplotlib was using. **Without** the `MPLBACKEND: Agg` environment variable set, then the Ubuntu machines would use "agg", the macOS machines would use "MacOSX", and the Windows machines would use "TkAgg" (see https://github.com/microsoft/torchgeo/runs/4316379792). **With** the environment variable set, then all machines would use "agg".

**Comment by adamjstewart** [comment]
Can we move the MPLBACKEND stuff into a separate PR (or just merge this PR now) so that other PRs can benefit from this change without having to wait for this PR to be finished?

**Comment by calebrob6** [comment]
Yeah sure, just merge this!

**Review by adamjstewart — APPROVED** [review]

**Comment by adamjstewart** [comment]
> I do not know if the env variable should go elsewhere

I think this location is fine. We could only enable it for the actual `pytest` step and only on Windows, but I don't see any issues with using Agg on macOS too.

**Pull request merged**
