### PR TITLE
README: add color lexing to bibtex

### PR DESCRIPTION
**Pull request by adamjstewart**
Looks nicer with color: https://github.com/adamjstewart/torchgeo/tree/readme/bib?tab=readme-ov-file#citation

### CODE REVIEW

**Comment by calebrob6** [comment]
Weird, I'm not seeing anything different:

image

**Comment by calebrob6** [comment]
I think "```bibtex" is correct, but it doesn't get rendered differently in markdown (but does in my editor after specifying bibtex)

image

**Comment by adamjstewart** [comment]
That's what I tried first but it didn't seem to work, then it did start to work. I think it's a browser caching thing. Let's try bibtex again.

**Comment by adamjstewart** [comment]
Still seems buggy. It renders with colors for a second during a refresh and then goes back to black-and-white.

**Comment by calebrob6** [comment]
I agree / observed the same

**Comment by adamjstewart** [comment]
It works in this example: https://github.com/awesome-spectral-indices/awesome-spectral-indices?tab=readme-ov-file#citation

I say we merge and assume it will work.

**Review by calebrob6 — APPROVED** [review]

**Pull request merged**
