### PR TITLE
plotting method Cyclone dataset

### PR DESCRIPTION
**Pull request by nilsleh**
Adding plotting method for Cyclone dataset.
cyclone

### CODE REVIEW

**Comment by nilsleh** [comment]
In eurosat.py for example, there is a boolean show_titles, which controls whether or not to show the label/prediction. Should I do it like that?

**Comment by adamjstewart** [comment]
Yep, I think that's what we want to do here.

**Comment by nilsleh** [comment]
In #288, it was mentioned that in case of predictions, the sample contains "predictions" as a key, however, in eurosat.py, the key in the sample is "prediction" without s. which of the two should it be?

**Comment by adamjstewart** [comment]
I think "prediction" is correct, none of our other keys (image, mask, label) are plural.

**Review by calebrob6 — APPROVED** [review]

**Pull request merged**
