### PR TITLE
Align Sentinel-2 band names in EuroSAT and transforms tutorial

### LINKED ISSUE #1635: Inconsistency in Sentinel 2 band names in transforms tutorial and eurosat dataset
### Issue

In the [tutorial](https://torchgeo.readthedocs.io/en/stable/tutorials/transforms.html) they are `B1`, `B2` etc but in [the dataset](https://github.com/microsoft/torchgeo/blob/main/torchgeo/datasets/eurosat.py) `B01`, `B02` etc. To avoid confusion it would be good to stick to one format. I've noticed this whilst adapting the tutorial

### Fix

Sitck to `B01`, `B02` etc

### PR DESCRIPTION
**Pull request by burakekim**
Fixes #1635

### CODE REVIEW

**Comment by adamjstewart** [comment]
> Could not push the PR before adressing this

Solution 1: update your copy of scikit-image to the latest version

Solution 2: stop using precommit (I don't even use it)

**Review by adamjstewart — APPROVED** [review]
Looks good, just need to undo changes to VHR10.

**Comment by burakekim** [comment]
Thanks! All the tests should pass once pytest starts functioning normally...

**Review by adamjstewart — APPROVED** [review]

**Comment by burakekim** [comment]
@adamjstewart Any idea why `pytest (ubuntu-latest, 3.10) (pull_request)` is keep failing? Anything I can do?

**Comment by adamjstewart** [comment]
Moving to 0.6.0 because it's technically backwards incompatible

**Pull request merged**
