### PR TITLE
Add NAIPCluster dataset and datamodule

### PR DESCRIPTION
**Pull request by calebrob6**
Dataset of NAIP imagery sampled random from the NAIP archive and masks generated by a KMeans clustering of pixels on-the-fly.

image

image

### CODE REVIEW

**Comment by adamjstewart** [comment]
How is this dataset different than our existing `NAIP` dataset with a new sampler? Basically, I'm wondering if this should be a sampler instead.

**Comment by calebrob6** [comment]
It creates masks by clustering the inputs

**Comment by adamjstewart** [comment]
Couldn't that be done as a transform? Then it could be combined with any dataset, not just NAIP.

If we make this a VisionDataset then we're throwing away all geospatial metadata.

**Comment by calebrob6** [comment]
(see my edit above)

Hmm the transform would need to take the model you want to use as input, so that would be a little cumbersome. Roughly you'd have to do:
```
# sample a bunch of NAIP imagery
# train a cluster model (using the more complicated logic for including windows if necessary)
# create a transform with that cluster model as input
# create another NAIP dataset with that transform
```

**Comment by calebrob6** [comment]
It isn't urgent that we figure this out (or crucial that this be in torchgeo) -- I'll be using this dataset in my own experiments though so I wanted a branch _somewhere_.

**Comment by adamjstewart** [comment]
I'm less opposed to adding this dataset to TorchGeo now that it's published and has some citations if you still want to add this.

**Comment by calebrob6** [comment]
Closing as ancient -- I _really_ like this idea, but probably belongs in a research repo or as some sort of dataset wrapper object. E.g. imagine if you could do:
```
ds = KMeansWrapper(NAIP(root=...))
```
which automatically added a "mask". Similarly I've wanted to add a DistanceToClassWrapper that you can use with segmentation datasets that compute a distance transform to a particular class in an existing mask. This would allow you to use boundary based losses without having to pre-compute distance.

@isaaccorley for thoughts

**Pull request closed without merging**
