### PR TITLE
issue #2006

### PR DESCRIPTION
**Pull request by Thakor-Yashpal**

### CODE REVIEW

**Comment by adamjstewart** [comment]
I think you need to install furo in order for the docs to build. You can add furo to `requirements/docs.txt` and `pyproject.toml` and try again. Later we'll figure out the minimum version that actually works.

P.S. You don't need to create a new PR each time, you can just push more commits to the same PR.

**Review by Thakor-Yashpal — COMMENTED** [review]
Is this correct or incorrect? Did I make any mistakes?

**Comment by adamjstewart** [comment]
Looks like our sphinx version is too old, you'll need to update that too.

**Comment by Thakor-Yashpal** [comment]
It's okay if it takes time to work on it; I'm working on it.

**Comment by adamjstewart** [comment]
Let me know if you need any more help.

**Comment by Thakor-Yashpal** [comment]
I'd like to give it another try.

**Pull request closed without merging**
