### PR TITLE
So2Sat: rename bands

### PR DESCRIPTION
**Pull request by adamjstewart**
Follow-up to #394 

I think it's better to ensure that all band names in So2Sat match the band names used in our Sentinel datasets. Since some bands come from Sentinel-1 and some bands come from Sentinel-2, the best way to handle this is to prefix `S1_` and `S2_` in front of all bands.

Alternative: do Sentinel-1 bands really go by B1, B2, ...? I see a lot of VV/VH/HV/HH online. Someone should implement a `Sentinel1` dataset so we can match that. If the bands no longer use B# names, we can drop the prefix from all bands.

@nilsleh

### CODE REVIEW

**Review by isaaccorley — APPROVED** [review]

**Comment by calebrob6** [comment]
An FYI: what the S1_* bands correspond to is specified here https://github.com/zhu-xlab/So2Sat-LCZ42#description-of-the-content-of-sen1

**Comment by adamjstewart** [comment]
Opened #821 to start on this. It seems like Sentinel-1 bands are named 001, 002, ..., 005, 006. Do we want to use S1_001 and S2_B1 for consistency with S1/S2, or S1_B1 and S2_B01 for internal consistency?

**Comment by nilsleh** [comment]
I don't have an opinion on this but also haven't been long enough in this area to know how much people would care. I think as long as the band correspondence is clearly documented either way is fine.

**Comment by adamjstewart** [comment]
Not sure if this should influence the decision made in this PR, but in #821 we ultimately went with HH, HV, VV, VH instead of 001, 002, ... for the band names.

**Pull request merged**
