### PR TITLE
Fixing network calls in unit tests

### LINKED ISSUE #194: Unit tests require internet access
In #185, @ashnair1 reported that our CI was failing because the trainer tests require internet access:
```
=================================== FAILURES ===================================
_____________________ TestLandCoverAITrainer.test_unet_ce ______________________

self = <tests.trainers.test_landcoverai.TestLandCoverAITrainer object at 0x1427c0160>
default_config = {'encoder_name': 'resnet18', 'encoder_output_stride': 16, 'encoder_weights': 'imagenet', 'learning_rate': 0.001, ...}

    def test_unet_ce(self, default_config: Dict[str, Any]) -> None:
        default_config["segmentation_model"] = "unet"
        default_config["loss"] = "ce"
>       task = LandcoverAISegmentationTask(**default_config)

tests/trainers/test_landcoverai.py:26: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
torchgeo/trainers/landcoverai.py:92: in __init__
    self.config_task()
torchgeo/trainers/landcoverai.py:41: in config_task
    self.model = smp.Unet(
../../../hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/segmentation_models_pytorch/unet/model.py:65: in __init__
    self.encoder = get_encoder(
../../../hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/segmentation_models_pytorch/encoders/__init__.py:62: in get_encoder
    encoder.load_state_dict(model_zoo.load_url(settings["url"]))
../../../hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/torch/hub.py:571: in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
../../../hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/torch/hub.py:459: in download_url_to_file
    buffer = u.read(8192)
../../../hostedtoolcache/Python/3.8.12/x64/lib/python3.8/http/client.py:459: in read
    n = self.readinto(b)
../../../hostedtoolcache/Python/3.8.12/x64/lib/python3.8/http/client.py:503: in readinto
    n = self.fp.readinto(b)
../../../hostedtoolcache/Python/3.8.12/x64/lib/python3.8/socket.py:669: in readinto
    return self._sock.recv_into(b)
../../../hostedtoolcache/Python/3.8.12/x64/lib/python3.8/ssl.py:1241: in recv_into
    return self.read(nbytes, buffer)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <ssl.SSLSocket [closed] fd=60, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0>
len = 7704, buffer = <memory at 0x1423dcdc0>

    def read(self, len=1024, buffer=None):
        """Read up to LEN bytes and return them.
        Return zero-length string on EOF."""
    
        self._checkClosed()
        if self._sslobj is None:
            raise ValueError("Read on closed or unwrapped SSL socket.")
        try:
            if buffer is not None:
>               return self._sslobj.read(len, buffer)
E               ConnectionResetError: [Errno 54] Connection reset by peer

../../../hostedtoolcache/Python/3.8.12/x64/lib/python3.8/ssl.py:1099: ConnectionResetError
----------------------------- Captured stderr call -----------------------------
Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /Users/runner/.cache/torch/hub/checkpoints/resnet18-5c106cde.pth

  0%|          | 0.00/44.7M [00:00<?, ?B/s]
  3%|▎         | 1.49M/44.7M [00:00<00:00, 50.6MB/s]

---------- coverage: platform darwin, python 3.8.12-final-0 ----------
Coverage XML written to file coverage.xml

=========================== short test summary info ============================
FAILED tests/trainers/test_landcoverai.py::TestLandCoverAITrainer::test_unet_ce
=========== 1 failed, 514 passed, 66 deselected in 83.95s (0:01:23) ============
Error: Process completed with exit code 1.
```
We should see if it's possible to monkeypatch things to skip downloads/pre-trained models for testing.

### PR DESCRIPTION
**Pull request by calebrob6**
closes #194

I made a mock resnet50 checkpoint file with all zeros so it would compress well, then made the test extract that file, monkey patched torchgeo.models.resnet to use that file, and monkey patched `load_state_dict_from_url` to load a state dict from file.

### CODE REVIEW

**Comment by calebrob6** [comment]
@adamjstewart is there a way we can prevent internet access on the tests to see what fails? My other thought is to temporarily assert pretrained is false before all model inits.

**Comment by adamjstewart** [comment]
This has some interesting ideas: https://stackoverflow.com/questions/18601828/python-block-network-connections-for-testing-purposes

We've thought about this in Spack too since a lot of tests require internet access and we want to avoid builds downloading dependencies automatically. I don't think we've decided on anything yet.

**Comment by calebrob6** [comment]
Looks like we'd have to do something to every test file... Want to see if the above fixes the failures and, if not, come back to it?

**Comment by adamjstewart** [comment]
Tested this on my laptop by clearing PyTorch's cache (`~/.cache/torch`), turning off WiFi, and running the tests. I'm still seeing a lot of tests that require internet access:
```
tests/trainers/test_byol.py .EEEEEEEE..                                                                                                                            [ 78%]
tests/trainers/test_chesapeake.py ..                                                                                                                               [ 78%]
tests/trainers/test_classification.py EEEE.F...EEEE.F..............................EEEE.F................................EEEF....                                  [ 87%]
tests/trainers/test_landcoverai.py ...                                                                                                                             [ 88%]
tests/trainers/test_naipchesapeake.py .                                                                                                                            [ 88%]
tests/trainers/test_regression.py EEEE.                                                                                                                            [ 88%]
tests/trainers/test_resisc45.py .                                                                                                                                  [ 88%]
tests/trainers/test_segmentation.py ..................                                                                                                             [ 90%]
tests/trainers/test_so2sat.py E..E..E..E..E..E..E..E..E..E..E..E..E..E............................                                                                 [ 97%]
tests/trainers/test_utils.py ..........                                                                                                                            [ 98%]
```

**Comment by calebrob6** [comment]
@adamjstewart, couple changes here:
- Deleted the So2Sat trainer as there didn't seem to be anything in it that was custom compared to the classification task and keeping it would be a pain to test now that we've removed imagenet pretrained model downloading. I verified that train.py works with so2sat + the classification trainer.
- Removed using imagenet pretrained weights from everywhere in the tests. This required parameterizing the regression task config (previously defaulted to use pretrained weights)

Can you check on your laptop again?

**Review by adamjstewart — APPROVED** [review]
Passes all tests without internet access! Great job!!

**Pull request merged**
