### PR TITLE
Add script to compress dataset files

### PR DESCRIPTION
**Pull request by adamjstewart**
This is hopefully the final script we need for dataset preprocessing. It allows us to map from the raw float32 files we downloaded to uint8 files while still capturing the majority of information. Reflectance bands were scaled using GEE visualization parameters. Temperature bands were scaled using NASA visualization parameters. Validation was done by computing statistics on the new datasets and visualizing the resulting bands in QGIS. Dataset size reduction is on the order of 15% of the original size.

### CODE REVIEW

**Comment by calebrob6** [comment]
Do these need to be compressed? Going from 12 or 14 bit (don't remember which) to 8 bit removes a lot of information.

**Comment by adamjstewart** [comment]
> Do these need to be compressed? Going from 12 or 14 bit (don't remember which) to 8 bit removes a lot of information.

We're going from float32 to uint8, it's a much bigger compression. ImageNet and CIFAR are also uint8. The SSL4EO-S12 paper actually experimented with this and found that uint8 resulted in better pre-trained models than uint16, see Appendix C1 and Table XVII of https://arxiv.org/pdf/2211.07044.pdf.

**Comment by adamjstewart** [comment]
Histograms:

### L7 L1

l7-l1

### L7 L2

l7-l2

### L8 L1

l8-l1

### L8 L2

l8-l2

Script used to generate in case I need to redo:
```python
import glob

import matplotlib.pyplot as plt
import numpy as np
import rasterio as rio

data = []
for file in glob.iglob("data/ssl4eo-l7-l2-v2/imgs/*/*/all_bands.tif"):
    with rio.open(file) as f:
        x = f.read().flatten()
        data.append(x)

plt.hist(data, bins=256, range=(0, 255))
plt.show()
```
This was for all 644 scenes I have downloaded on my laptop. I can make separate plots per band or for a smaller set of images if you prefer.

**Comment by calebrob6** [comment]
Just over 1 band, and I think this is doing something weird, can you do `f.read(1)` and `data = np.concatenate(data, axis=0)`, then maybe log scale the yaxis?

**Review by calebrob6 — APPROVED** [review]

**Comment by calebrob6** [comment]
> We're going from float32 to uint8, it's a much bigger compression. ImageNet and CIFAR are also uint8. The SSL4EO-S12 paper actually experimented with this and found that uint8 resulted in better pre-trained models than uint16, see Appendix C1 and Table XVII of https://arxiv.org/pdf/2211.07044.pdf.

They are reporting best performance with unnormalized uint8 values as input to the network?

**Comment by adamjstewart** [comment]
I believe so, @wangyi111?

**Comment by calebrob6** [comment]
> I think this is doing something weird

The different colors on the plots make me think it is plotting a histogram for each image separately. You want, e.g., a single histogram of all the values in the red band.

**Comment by wangyi111** [comment]
> They are reporting best performance with unnormalized uint8 values as input to the network?

Yes, but I won't say that's the "best". I would go for "similar", while uint8 would save tons of storage. 

On the other hand, I checked only land cover classification task though. The raw float32 reflectance values might be useful for specific fine-grained tasks, which I am not so familiar.

**Comment by wangyi111** [comment]
> Dataset size reduction is on the order of 15% of the original size.

Why only 15%? from 32bit to 8bit I suppose much more compression.

**Comment by adamjstewart** [comment]
I don't mean 100% to 85%, I mean 100% to 15%. So 75% decrease due to float32 -> uint8 and another 10% due to LZW compression.

**Comment by isaaccorley** [comment]
Running this doesn't actually print any progress bar for me. Is there something else we should be passing to `thread_map` to show progress?

**Comment by adamjstewart** [comment]
That's weird, it prints a progress bar for me. I'm using tqdm 4.65.0.

**Comment by adamjstewart** [comment]
@calebrob6 you were correct, here are the correct histograms for B1:

### L7 L1

l7-l1

### L7 L2

l7-l2

### L8 L1

l8-l1

### L8 L2

l8-l2

**Comment by isaaccorley** [comment]
Nevermind about the progress bar. It acts different inside my vscode terminal but in a regular terminal it prints fine.

**Review by calebrob6 — APPROVED** [review]

**Comment by calebrob6** [comment]
No changes, but from the histograms you can see the values bunched up over a relatively small range. I'm guessing this is a place where you could get incremental improvement by playing with the percentiles you use for min and max (as it would spread these distributions out).

**Pull request merged**
