### PR TITLE
README: add Hugging Face badge

### PR DESCRIPTION
**Pull request by adamjstewart**
One more badge for our community. The logo is not yet recognized but will work once https://github.com/simple-icons/simple-icons/pull/9259 is merged.

Also fixed the color of the Slack logo to match the brand guidelines: https://brand.slackhq.com/color

Thoughts on the order of these badges? The colors all clash a bit...

### CODE REVIEW

**Comment by adamjstewart** [comment]
Thought about adding TorchGeo to simple-icons but we don't (yet) meet their popularity criteria: https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity

**Comment by robmarkcole** [comment]
LGTM!

**Comment by ashnair1** [comment]
Maybe flip the OSGeo and Hugging face badges so it sort of follows the EM spectrum? :) Looks fine either way.

**Comment by adamjstewart** [comment]
Yep, that looks less jarring. Thanks!

**Review by ashnair1 — APPROVED** [review]

**Pull request merged**
