### PR TITLE
Fix version selection button in docs

### PR DESCRIPTION
**Pull request by adamjstewart**
Want to see if this fixes the broken version selection button.

### CODE REVIEW

**Comment by adamjstewart** [comment]
Okay, 5.3.0 works, let's try 6.0.0 to confirm that that's the version that broken pytorch-sphinx-theme.

**Comment by adamjstewart** [comment]
And 6.0.0 breaks, will open an issue.

**Comment by adamjstewart** [comment]
https://github.com/pytorch/pytorch_sphinx_theme/issues/175

**Comment by adamjstewart** [comment]
We may want to reconsider switching to trojanzoo_sphinx_theme since it seems to actually be supported.

**Review by calebrob6 — APPROVED** [review]

**Comment by calebrob6** [comment]
This also fixes the floating menus (these break with the version selector)

**Pull request merged**
