### PR TITLE
Update VHR-10 dataset plotting

### PR DESCRIPTION
**Pull request by robmarkcole**
Fix plotting using percentiles

Note: I have uploaded the dataset at https://huggingface.co/datasets/satellite-image-deep-learning/VHR-10 - can transfer to torchgeo org if you want to use it here

### CODE REVIEW

**Comment by robmarkcole** [comment]
I just assumed the docs predate the datamodules but we would like to showcase this feature - personally I always use datamodules now but perhaps am in the minority there. Suggest a second opinion before I change the PR

**Comment by robmarkcole** [comment]
@ashnair1  I checked the approach I suggested (`imgIds=id_)`) and this results in erroneous masks - strange as the API appears to support this approach, suggesting the dataset has some quirks

image

**Comment by adamjstewart** [comment]
### Regarding the README

The README has a few different sections. The section you're editing is designed to show off our benchmark _datasets_. There is a separate section below specifically for PyTorch Lightning, including _data modules_. I would prefer to keep using a dataset instead of a data module here. 

Actually, I think we're better off choosing a different dataset (maybe EuroSAT?). VHR-10 is too complicated and makes it look like TorchGeo is hard to use. Maybe we could move VHR-10 to the Lightning section of the README since it has a pretty visualization.

### Regarding plotting

Yes, this is a common issue with plotting via dataset vs. plotting via data module. I agree with your solution, and proposed basically the same thing for all datasets in #1263. This issue is not specific to VHR-10, but affects almost all datasets/data modules. I haven't had the time/energy to fix this for all datasets, but contributions are definitely welcome here, even if it's only 1 dataset at a time.

Can we separate the README and plotting changes into two separate PRs?

**Comment by adamjstewart** [comment]
> Note: I have uploaded the dataset at https://huggingface.co/datasets/satellite-image-deep-learning/VHR-10 - can transfer to torchgeo org if you want to use it here

It's easier to download tar/zip/rar files instead of raw data. But I'm happy to change the download to your org or ours. Not sure if we should rehost all rar datasets as tar/zip to make them easier to extract?

**Comment by robmarkcole** [comment]
@adamjstewart this PR now just addresses the plotting.

RE dataset choice, I agree EuroSAT would be a nice choice - it also supports selecting subsets of bands so shows immediately what is possible with torchgeo

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
