### PR TITLE
Trainers: fix plotting file handle leak

### LINKED ISSUE #825: Figures not closed
### Description

I think there's a memory leak here:
> [WARNING] /opt/conda/lib/python3.8/site-packages/torchgeo/datasets/nasa_marine_debris.py:246: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).

### Steps to reproduce

Run `NASAMarineDebrisDataModule` for > 5 epochs

### Version

latest

### PR DESCRIPTION
**Pull request by adamjstewart**
@austinmw can you see if this fixes #825?

### CODE REVIEW

**Comment by calebrob6** [comment]
I thought we were already doing this?

**Comment by adamjstewart** [comment]
This came up before but in our unit tests. This hasn't come up before with our trainers/datamodules.

**Review by calebrob6 — APPROVED** [review]

**Comment by austinmw** [comment]
> @austinmw can you see if this fixes #825?

will do tomorrow morning

**Comment by austinmw** [comment]
@adamjstewart successfully removed the warning for me

**Pull request merged**
