### PR TITLE
Correct the seco weight names

### LINKED ISSUE #1234: SeCo weights issue warning when loaded
### Description

It seems like the SeCo weights still have the final layer from when they were trained, meaning they always issue a warning when loaded into a trainer. We should remove the last layer and make sure the only keys in the weight are the ones needed to load the model.

### Steps to reproduce

Any of the following commands will reproduce the warning:
```console
$ pytest -m slow tests/trainers/test_regression.py::TestRegressionTask::test_weight_enum_download[ResNet50_Weights.SENTINEL2_RGB_SECO]
$ pytest -m slow tests/trainers/test_regression.py::TestRegressionTask::test_weight_str_download[ResNet50_Weights.SENTINEL2_RGB_SECO]
$ pytest -m slow tests/trainers/test_classification.py::TestClassificationTask::test_weight_enum_download[ResNet50_Weights.SENTINEL2_RGB_SECO]
$ pytest -m slow tests/trainers/test_classification.py::TestClassificationTask::test_weight_str_download[ResNet50_Weights.SENTINEL2_RGB_SECO]
```
No other weights issue this warning. We could ignore it with `with pytest.warns():`, but this will cause all other weights to fail the tests since they don't issue a warning.

### Version

0.5.0.dev0 (35525b2eb9cd53bf1910f2f6bd7714584205d927)

### PR DESCRIPTION
**Pull request by nilsleh**
Closes #1234

### CODE REVIEW

**Comment by adamjstewart** [comment]
Having trouble reproducing the original issue so it's hard for me to verify that it's now fixed.

**Comment by calebrob6** [comment]
```
old_keys = set(torch.load("resnet18_sentinel2_rgb_seco-9976a9cb.pth").keys())
new_keys = set(torch.load("resnet18_sentinel2_rgb_seco-c2e6e88b.pth").keys())

print(old_keys - new_keys)
```
Gives:
```
{'layer3.0.bn1.bias',
 'layer3.0.bn1.num_batches_tracked',
 'layer3.0.bn1.running_mean',
 'layer3.0.bn1.running_var',
 'layer3.0.bn1.weight',
 'layer3.0.bn2.bias',
 'layer3.0.bn2.num_batches_tracked',
 'layer3.0.bn2.running_mean',
 'layer3.0.bn2.running_var',
 'layer3.0.bn2.weight',
 'layer3.0.conv1.weight',
 'layer3.0.conv2.weight',
 'layer3.0.downsample.0.weight',
 'layer3.0.downsample.1.bias',
 'layer3.0.downsample.1.num_batches_tracked',
 'layer3.0.downsample.1.running_mean',
 'layer3.0.downsample.1.running_var',
 'layer3.0.downsample.1.weight',
 'layer3.1.bn1.bias',
 'layer3.1.bn1.num_batches_tracked',
 'layer3.1.bn1.running_mean',
 'layer3.1.bn1.running_var',
 'layer3.1.bn1.weight',
 'layer3.1.bn2.bias',
 'layer3.1.bn2.num_batches_tracked',
 'layer3.1.bn2.running_mean',
 'layer3.1.bn2.running_var',
 'layer3.1.bn2.weight',
 'layer3.1.conv1.weight',
 'layer3.1.conv2.weight',
 'layer4.0.bn1.bias',
 'layer4.0.bn1.num_batches_tracked',
 'layer4.0.bn1.running_mean',
 'layer4.0.bn1.running_var',
 'layer4.0.bn1.weight',
 'layer4.0.bn2.bias',
 'layer4.0.bn2.num_batches_tracked',
 'layer4.0.bn2.running_mean',
 'layer4.0.bn2.running_var',
 'layer4.0.bn2.weight',
 'layer4.0.conv1.weight',
 'layer4.0.conv2.weight',
 'layer4.0.downsample.0.weight',
 'layer4.0.downsample.1.bias',
 'layer4.0.downsample.1.num_batches_tracked',
 'layer4.0.downsample.1.running_mean',
 'layer4.0.downsample.1.running_var',
 'layer4.0.downsample.1.weight',
 'layer4.1.bn1.bias',
 'layer4.1.bn1.num_batches_tracked',
 'layer4.1.bn1.running_mean',
 'layer4.1.bn1.running_var',
 'layer4.1.bn1.weight',
 'layer4.1.bn2.bias',
 'layer4.1.bn2.num_batches_tracked',
 'layer4.1.bn2.running_mean',
 'layer4.1.bn2.running_var',
 'layer4.1.bn2.weight',
 'layer4.1.conv1.weight',
 'layer4.1.conv2.weight'}
```

**Comment by nilsleh** [comment]
> @nilsleh, is this correct? The new weights don't have any entries for layer 3 or layer 4.

I used the script you posted in the issue to update the weights and didn't check further. I will look into again.

**Comment by calebrob6** [comment]
Oh oops... sorry for leading you in the wrong direction here! Good to not trust my code unless it has been reviewed by Adam.

**Comment by nilsleh** [comment]
> Oh oops... sorry for leading you in the wrong direction here! Good to not trust my code unless it has been reviewed by Adam.

Sorry, turns out the mistake was on my end of course, just always better to first blame others...

**Comment by adamjstewart** [comment]
Still curious how to reproduce the original issue so I can confirm that things have actually been fixed. If our (slow) tests don't catch this bug, then I'm worried about our tests.

**Comment by calebrob6** [comment]
```
from lightning import LightningModule
import timm
import torch
from copy import deepcopy
from torch import nn
import torchvision

class MocoV2(LightningModule):

    def __init__(self, base_encoder, emb_dim, num_negatives, emb_spaces=1, *args, **kwargs):
        super().__init__()
        self.save_hyperparameters()

        # create the encoders
        template_model = getattr(torchvision.models, base_encoder)
        self.encoder_q = template_model(num_classes=self.hparams.emb_dim)
        self.encoder_k = template_model(num_classes=self.hparams.emb_dim)

        # remove fc layer
        self.encoder_q = nn.Sequential(*list(self.encoder_q.children())[:-1], nn.Flatten())
        self.encoder_k = nn.Sequential(*list(self.encoder_k.children())[:-1], nn.Flatten())

        for param_q, param_k in zip(self.encoder_q.parameters(), self.encoder_k.parameters()):
            param_k.data.copy_(param_q.data)  # initialize
            param_k.requires_grad = False  # not update by gradient

        # create the projection heads
        self.mlp_dim = 512 * (1 if base_encoder in ['resnet18', 'resnet34'] else 4)
        self.heads_q = nn.ModuleList([
            nn.Sequential(nn.Linear(self.mlp_dim, self.mlp_dim), nn.ReLU(), nn.Linear(self.mlp_dim, emb_dim))
            for _ in range(emb_spaces)
        ])
        self.heads_k = nn.ModuleList([
            nn.Sequential(nn.Linear(self.mlp_dim, self.mlp_dim), nn.ReLU(), nn.Linear(self.mlp_dim, emb_dim))
            for _ in range(emb_spaces)
        ])

        for param_q, param_k in zip(self.heads_q.parameters(), self.heads_k.parameters()):
            param_k.data.copy_(param_q.data)  # initialize
            param_k.requires_grad = False  # not update by gradient

        # create the queue
        self.register_buffer("queue", torch.randn(emb_spaces, emb_dim, num_negatives))
        self.queue = nn.functional.normalize(self.queue, dim=1)

        self.register_buffer("queue_ptr", torch.zeros(emb_spaces, 1, dtype=torch.long))

if __name__ == "__main__":
    backbone = MocoV2.load_from_checkpoint("../seasonal-contrast/seco_resnet50_1m.ckpt")
    model = deepcopy(backbone.encoder_q).eval()
    state_dict_original = model.state_dict()

    patient_model = timm.create_model("resnet50")
    key_correct_name_list = list(patient_model.state_dict().keys())

    state_dict_new = {}
    for i, (k, v) in enumerate(state_dict_original.items()):
            state_dict_new[key_correct_name_list[i]] = v
    print(patient_model.load_state_dict(state_dict_new, strict=False))

    torch.save(patient_model.state_dict(), "seco_resnet50_1m.ckpt")
```

**Review by adamjstewart — DISMISSED** [review]
Figured out how to test, just need to run the slow tests `pytest -m slow tests/models` and either make it strict or assert that there are no missing/unexpected keys.

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
