### PR TITLE
Citation: arXiv -> SIGSPATIAL

### PR DESCRIPTION
**Pull request by adamjstewart**
No idea if these keys are correct. Also need to update the README.

### CODE REVIEW

**Comment by calebrob6** [comment]
Schema here https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md

**Comment by calebrob6** [comment]
Currently creates bibtext like:
```
@inproceedings{Stewart_TorchGeo_Deep_Learning_2022,
	author = {Stewart, Adam J. and Robinson, Caleb and Corley, Isaac A. and Ortiz, Anthony and Lavista Ferres, Juan M. and Banerjee, Arindam},
	doi = {10.1145/3557915.3560953},
	month = {11},
	pages = {1--12},
	publisher = {Association for Computing Machinery},
	title = {{TorchGeo: Deep Learning With Geospatial Data}},
	url = {https://github.com/microsoft/torchgeo},
	year = {2022}
}
```

Only thing that is missing is the `booktitle={Proceedings of the 30th International Conference on Advances in Geographic Information Systems},` key in the bibtex.

**Comment by adamjstewart** [comment]
Also missing SIGSPATIAL entirely, I wish they documented which keys they support cuz they don't match bibtex.

**Review by calebrob6 — APPROVED** [review]

**Comment by calebrob6** [comment]
@adamjstewart I fixed it

**Comment by adamjstewart** [comment]
Alright, I think this is about as good as it gets.

**Review by calebrob6 — APPROVED** [review]

**Pull request merged**
