### PR TITLE
Moving BigEarthNet sort_bands function into utils as sort_sentinel2_bands

### PR DESCRIPTION
**Pull request by iejMac**

### CODE REVIEW

**Comment by calebrob6** [comment]
@iejMac check out the notes [here](https://torchgeo.readthedocs.io/en/latest/user/contributing.html#linters) for why the checks are complaining. If you use vscode (other IDE like things probably support this too) you can configure it to run linting inline (i.e. have it underline stuff in red).

**Comment by calebrob6** [comment]
I use a Makefile to quickly see if anything will break before I push (you can also setup pre-commit but I found that to be annoying):

```
.PHONY: tests docs

tests:
	black --check .
	isort . --check --diff
	flake8 .
	pydocstyle .
	mypy .
	pytest --cov=. --cov-report=term-missing

docs:
	$(MAKE) -C docs html
```

**Review by calebrob6 — APPROVED** [review]

**Comment by calebrob6** [comment]
This looks good to me, I'm going to merge it overriding whatever happened with the ImageFolder doc complaint

**Comment by isaaccorley** [comment]
This still needed to be added to __all__ at the top of torchgeo/datasets/utils.py but I don't think it's breaking.

**Comment by iejMac** [comment]
Sorry about that, added it in new PR

**Pull request merged**
