### PR TITLE
conda's environment.yml: install pytorch gpu by pegging cudatoolkit to <= v11.5

### LINKED ISSUE #529: Conda installs a cpu version of pytorch and torchvision
Conda installation (tested on Ubuntu 20.04) installs a cpu version of pytorch and torchvision. In my own project, the only remedy I've found was to [hardcode the pytorch package](https://github.com/remtav/geo-deep-learning/blob/222-stac-item-input/environment.yml#L9) to use. Poor solution. Hoping to find an alternative.

Related to #527 

result from `conda list` in torchgeo environment:
ksnip_20220503-162044
ksnip_20220503-162055

### PR DESCRIPTION
**Pull request by remtav**
Fixes #529

### CODE REVIEW

**Comment by ashnair1** [comment]
The docs issue was solved by a755bb62901d2a103ad4741bcb154a28bb33be37. Could you try rebasing from `main`?

**Comment by adamjstewart** [comment]
This hack will need to be updated with every new cudatoolkit release. Does switching from `pytorch` to `pytorch-gpu` also solve the issue?

**Comment by ashnair1** [comment]
Switching to `pytorch-gpu` will get us back to #293.

**Comment by ashnair1** [comment]
Also this isn't really required for every cudatoolkit release. Just the latest cudatoolkit that pytorch is compiled with. Hence why 11.5 is used instead of 11.7

**Comment by adamjstewart** [comment]
Looks like a bad rebase.

**Pull request closed without merging**
