### PR TITLE
Fixed string formatting and naming issues.

### PR DESCRIPTION
**Pull request by pioneerHitesh**
Fixed ``root={self.paths}`` in the ``datasets module`` and I have also fixed inconsistent ``root`` and ``path`` naming conventions.

### CODE REVIEW

**Comment by adamjstewart** [comment]
We try to use `root` for datasets that require a single directory and `paths` for datasets that support one or more directories or filenames. Most GeoDatasets support `paths`, but not all. That's part of the inconsistency, and we might want to keep that. All NonGeoDatasets only support `root`.

**Comment by pioneerHitesh** [comment]
@adamjstewart  ``mypy`` throws error for paths being of type ``str`` and ``Iterable[str]`` . It seems like we should add ``pathlib.path``  support first then we may embark on other removing ``os.path.expanduser()`` and renaming ``root`` to ``paths``. What is your take on this?

**Comment by adamjstewart** [comment]
The only thing I suggested to rename was `root={self.paths}` to `paths={self.paths!r}`, I didn't suggest renaming all `root` to `paths`. Mypy shouldn't touch this code since it's a string name.

**Comment by pioneerHitesh** [comment]
@adamjstewart can you please take a look at this [PR](https://github.com/microsoft/torchgeo/pull/1704)

**Comment by pioneerHitesh** [comment]
@adamjstewart i have removed ``os.path.expanduser`` in this [PR](https://github.com/microsoft/torchgeo/pull/1705). Can you please take a look?

**Comment by adamjstewart** [comment]
P.S. We're planning a 0.5.1 release next week, would be great to get this PR in if you want to remove the unrelated changes and stick to just updating the error messages.

**Comment by adamjstewart** [comment]
Nevermind, #1704 had all other changes, so I think this can be closed now.

**Comment by pioneerHitesh** [comment]
> P.S. We're planning a 0.5.1 release next week, would be great to get this PR in if you want to remove the unrelated changes and stick to just updating the error messages.

Sorry for the belated reply, but i may not be able to help you out with this.

**Pull request closed without merging**
