### PR TITLE
Update kornia version in environment.yml

### PR DESCRIPTION
**Pull request by ashnair1**

### CODE REVIEW

**Comment by ashnair1** [comment]
Tests are failing due to an issue with `protobuf`. 

Ref: PyTorchLightning/pytorch-lightning#13159

**Comment by adamjstewart** [comment]
Maybe we should pin protobuf to a lower version for now so it doesn't hold up other PRs?

**Comment by ashnair1** [comment]
Yeah that seems like the proposed fix.

**Comment by ashnair1** [comment]
Updated codecov-action to address codecov/codecov-action#745

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
