### PR TITLE
TropicalCyclone dataset: use target for sample key

### PR DESCRIPTION
**Pull request by adamjstewart**
This dataset uses a random key name "wind_speed" instead of a more typical name like "target". This makes it harder to combine with other regression datasets using a single trainer.

Once this is merged I'm planning to refactor things to make a single `RegressionTask` trainer that I can use for Cyclone, COWCCounting, and other regression datasets.

### CODE REVIEW

**Review by isaaccorley — APPROVED** [review]
lgtm

**Comment by adamjstewart** [comment]
Apparently every other dataset uses "label", not "target". Going to change this again...

**Comment by adamjstewart** [comment]
I think "target" is too generic, targets can include "labels" (scalar), "masks" (matrix), etc.

**Comment by isaaccorley** [comment]
True but in regression you generally have a target variable so it fits the lingo but I see what you're saying. Label is fine since it's obvious what it is.

**Pull request merged**
