### PR TITLE
Add plot method to base chesapeake

### PR DESCRIPTION
**Pull request by nilsleh**
This PR adds a plot method to the Chesapeake dataset baseclass to address #253. I was unable to run pytest, because the currently generated fake data cannot be unzipped:
`NotImplementedError: That compression method is not supported`

should I change the archive method in the base data.py class to the `shutil.make_archive()` used in other data.py files?

### CODE REVIEW

**Comment by adamjstewart** [comment]
This is done on purpose. Chesapeake data uses the proprietary deflate64 compression algorithm, so we want to use the same compression for the fake data. If you install `zipfile-deflate64` you should be able to decompress these files.

**Comment by calebrob6** [comment]
Chesapeake7 and 13 have their own cmaps, which plot should use. I can fill that in though.

**Comment by calebrob6** [comment]
Here's an image from the same crop of both datasets that show how the classes differ:

Chesapeake 13
image


Chesapeake 7
image

**Comment by calebrob6** [comment]
I did a few other things:
- Added a check in RasterDataset to not override cmap if cmap is already specified
- Fixed #419

**Comment by adamjstewart** [comment]
I have an alternative fix for #419 in #420 that might be cleaner.

**Comment by adamjstewart** [comment]
Also, the fix should be in a separate PR, otherwise we can't put it in 0.2.1.

**Comment by adamjstewart** [comment]
The cmap fix should be in a separate PR so we can backport it to 0.2.1.

**Review by calebrob6 — APPROVED** [review]

**Pull request merged**
