### PR TITLE
Move DataModules from torchgeo.trainers to torchgeo.datasets

### PR DESCRIPTION
**Pull request by adamjstewart**
See #205

### CODE REVIEW

**Comment by calebrob6** [comment]
anyway to do this without destroying the history?

**Comment by adamjstewart** [comment]
Not really. If it were a file rename we could use `git log --follow` but that won't work since we're appending to an existing file. I'm pretty sure GitHub used to let you see the history of files if you manually typed in the address of the old file path, but it doesn't seem to work anymore.

**Comment by calebrob6** [comment]
Sorry, I'm not following well -- are there any changes needed for this?

**Comment by adamjstewart** [comment]
Nope. You'll be able to see the history of the previous files, but only if you check out a commit from before this move.

**Review by calebrob6 — APPROVED** [review]

**Review by isaaccorley — APPROVED** [review]

**Pull request merged**
