### PR TITLE
Add download_radiant_mlhub_collection

### PR DESCRIPTION
**Pull request by ashnair1**
Closes microsoft/torchgeo#151

### CODE REVIEW

**Review by adamjstewart — COMMENTED** [review]
We should do one of the following things:

1. Rename `download_radiant_mlhub` to `download_radiant_mlhub_dataset`
2. Combine both methods into a single method that takes either `dataset_id` or `collection_id` but not both

Thoughts on these two options? I don't have a strong preference at the moment.

**Comment by ashnair1** [comment]
I would go with the renaming option. It's cleaner.

**Review by calebrob6 — DISMISSED** [review]

**Comment by ashnair1** [comment]
Coverage is reduced because import exception for `download_radiant_mlhub_collection` isn't covered.

**Comment by calebrob6** [comment]
I think I appeased it... Thanks @ashnair1!

**Review by calebrob6 — APPROVED** [review]

**Pull request merged**
