### PR TITLE
Add TorchGeo CLI tutorial

### PR DESCRIPTION
**Pull request by adamjstewart**
Basically copied the docs from the README to a tutorial.

### CODE REVIEW

**Comment by calebrob6** [comment]
`torchgeo validate` and `torchgeo test` won't use the trained model by default

**Comment by adamjstewart** [comment]
Yeah, I'm not sure if there's an easy way to know the name of the trained model checkpoint to use. Maybe we can specify the name to use? I wish `--best` worked.

**Comment by calebrob6** [comment]
You can setup a ModelCheckpoint to save last then point it to `/tmp/eurosat100/lightning_logs/version_0/checkpoints/last.ckpt`

**Comment by adamjstewart** [comment]
Hmm, I'll look into it, but I'm hoping to not make the config.yaml too complicated.

**Comment by calebrob6** [comment]
Then we need to be really clear that "torchgeo test" and "torchgeo validate" are just going to return results from a random initialized model (which is.... not helpful). I think a reader would expect "torchgeo test" to test the trained model as the tutorial is written currently. We should also show users how to _actually_ test their model too because that's going to be what people want to do with "test" or "validate" lol

**Comment by adamjstewart** [comment]
Fixed

**Review by calebrob6 — APPROVED** [review]

**Pull request merged**
