### PR TITLE
Add RESISC45 Dataset

### LINKED ISSUE #125: Add RESISC45 Dataset
We should look at adding the [RESISC45 dataset](http://www.escience.cn/people/JunweiHan/NWPU-RESISC45.html) from ["Remote Sensing Image Scene Classification: Benchmark and State of the Art", Cheng et al. (2017)](https://arxiv.org/abs/1703.00121).

It's an image classification dataset but is difficult due to inherently being noisy (high variance in spatial resolution, occlusion, illumination, weather conditions).

### PR DESCRIPTION
**Pull request by isaaccorley**
- Adds `torchgeo.datasets.RESISC45` from the ["Remote Sensing Image Scene Classification: Benchmark and State of the Art", Cheng et al. (2017)](https://arxiv.org/abs/1703.00121)
- Updated docs
- Added `tests/datasets/test_resisc45.py`
- Added sample data for tests under `tests/data/resisc45/`

Similar setup to the `torchgeo.datasets.PatternNet`

Closes #125

### CODE REVIEW

**Comment by isaaccorley** [comment]
Seems like the build is failing because of rar not being available on windows?

**Comment by isaaccorley** [comment]
Also, there's not much change between this dataset and PatternNet. I'm curious if we should consider making a VisionClassificationDataset to reduce boilerplate?

**Comment by adamjstewart** [comment]
> Seems like the build is failing because of rar not being available on windows?

Yes, we have the same problem with the `VHR10` dataset, just add this line:
https://github.com/microsoft/torchgeo/blob/main/tests/datasets/test_nwpu.py#L20

**Review by adamjstewart — DISMISSED** [review]

**Comment by adamjstewart** [comment]
> Also, there's not much change between this dataset and PatternNet. I'm curious if we should consider making a VisionClassificationDataset to reduce boilerplate?

Yeah, we probably should. I'm fine with waiting until we have more examples of this pattern before we standardize, or you can do it now.

**Comment by isaaccorley** [comment]
> > Also, there's not much change between this dataset and PatternNet. I'm curious if we should consider making a VisionClassificationDataset to reduce boilerplate?
> 
> Yeah, we probably should. I'm fine with waiting until we have more examples of this pattern before we standardize, or you can do it now.

I think I'll make a separate PR for this.

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
