### PR TITLE
Pin protobuf<4

### PR DESCRIPTION
**Pull request by ashnair1**
Tests were failing due to the recent release of protobuf 4.21.0. See protocolbuffers/protobuf#10051

Error propagation: protobuf > tensorboard > pytorch_lightning > torchgeo

### CODE REVIEW

**Review by adamjstewart — APPROVED** [review]
Thanks! Hopefully we can remove this soon.

**Comment by adamjstewart** [comment]
Looks like 4.21.0 was yanked so maybe the protobuf devs understand that this was a bad idea: https://pypi.org/project/protobuf/#history

If you rerun the tests on your other PR it might pass without needing this PR. Not sure if protobuf or tensorboard will get a new release first.

**Comment by ashnair1** [comment]
Not sure what's going on with this test failure. I could add the protobuf entry under pip in the environment.yml but I'm not sure that's the issue here.

Per the discussion in the linked issue, it might be a good idea to pin `protobuf=3.21.0` since it seems the devs still plan to push a 4.20.1

**Comment by adamjstewart** [comment]
Yeah, definitely pinning to `<4` is a good idea.

**Comment by adamjstewart** [comment]
I also have no idea why the Windows tests are failing. We don't use `environment.yml` in those tests so it can't be related to that.

**Comment by adamjstewart** [comment]
Can you rebase and also add this to `requirements.txt`?

**Review by adamjstewart — APPROVED** [review]

**Review by adamjstewart — DISMISSED** [review]

**Comment by ashnair1** [comment]
Ran into a failed coverage test (no idea why that happened). Pushed again to see if error reappears.

**Comment by adamjstewart** [comment]
No idea what's going on with coverage. You have all the same commits as main, so it's not like new code has been added and the absolute number of lines of coverage have changed...

Also, you'll probably want to add protobuf to the ignore list in `.github/dependabot.yml` so that dependabot doesn't try to update it.

There is a new release of protobuf now that hasn't been yanked, but there's also a new release of pytorch-lightning that pins protobuf to an older version, so we're technically good for now. PyTorch has also pinned to older protobuf and 1.12.0 seems poised for a release soon. Hopefully we won't need this for long.

**Comment by ashnair1** [comment]
> There is a new release of protobuf now that hasn't been yanked, but there's also a new release of pytorch-lightning that pins protobuf to an older version, so we're technically good for now. PyTorch has also pinned to older protobuf and 1.12.0 seems poised for a release soon. Hopefully we won't need this for long.

Wouldn't we then need to update the min version of pytorch-lightning and/or pytorch? Seems like a big jump from 1.3 to 1.6.5 and 1.7.0 to 1.12.0 respectively.

**Comment by adamjstewart** [comment]
No need to change the minimum versions, TorchGeo is still compatible with both the older and newer releases. Someone might need to manually install an older version of protobuf to get PyTorch or tensorboard working, but that's not a TorchGeo issue.

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
