### PR TITLE
add channels to prevent conda's ResolvePackageError on Windows

### LINKED ISSUE #527: Installation via conda raises ResolvePackageNotFound on Windows. Two conda channels missing for a fix.
On Windows (10), conda can't find torchvision nor pycocotools: 
```
(base) C:\Users\...>conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - torchvision[version='>=0.10']
  - pycocotools
```
Adding `pytorch` and `esri` in [channels of environment.yml](https://github.com/microsoft/torchgeo/blob/main/environment.yml#L2) seems to fix this issue.

### PR DESCRIPTION
**Pull request by remtav**
fixes #527

### CODE REVIEW

**Comment by calebrob6** [comment]
This looks good to me, I ran into similar issues a few weeks ago and came up with a similar solution

**Comment by calebrob6** [comment]
Why is the esri channel necessary?

**Comment by remtav** [comment]
> Why is the esri channel necessary?

pycocotools doesn't resolve with conda-forge channels on Windows. I simply took the [2nd most popular channel](https://anaconda.org/search?q=pycocotools) for this package.

**Review by calebrob6 — APPROVED** [review]

**Review by adamjstewart — APPROVED** [review]
I don't use conda so as long as @calebrob6 approves I'm happy

**Pull request merged**
